# Generated by Django 2.0.7 on 2018-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateField(default='2018-07-10')),
                ('updated_at', models.DateField(default='2018-07-10')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'TodoItems',
                'db_table': 'django_todo_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
