# Generated by Django 2.0.7 on 2018-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='input_text',
            field=models.TextField(blank=True),
        ),
    ]
